import mongoose from "mongoose";

const OfferWysiwygSchema = new mongoose.Schema({
    pageHeader: String,
    date: String,
    uniqueId: { type: Number, unique: true },
    generateUniqueId: String,
    doubleIdChecker: String,
    coralData: String,
    line: String,
    aquarium: Number,
    number: String,
    location: String,
    locationChecker: String,
    appsheetCode: String,
    cites: String,
    aliasCites1: String,
    code: String,
    latinName: String,
    commonName: String,
    size: String,
    marking: String,
    plasticSize: Number,
    heightCm: String,
    price: String,
    individualDiscount: String,
    citesCombo: String,
    citesScleractinianFragmen: String,
    cherryPickImage: String,
    exclusiveSection: String,
    exclusiveFor: String,
    duplicateImageSection: String,
    duplicateChecker: String,
    system: String,
    imageFileName: String,
    image: String,
    imageSale: String,
    imageChecker: String,
    orderStatus: String,
    orderByCartKey: String,
    orderByCrm: String,
    orderByUser: String,
    orderById: String,
    scriptResponse: String,
    show: String,
    textAllPriceMargin: String,
    textIndividualPriceMargin: String,
    link_image: Array,
}, { timestamps: true });

const OfferWysiwyg = mongoose.models.OfferWysiwyg || mongoose.model("OfferWysiwyg", OfferWysiwygSchema);
export default OfferWysiwyg;
