import mongoose from "mongoose";

const UserGsheetSchema = new mongoose.Schema({
    STARTING: String,
    KEY: String,
    USER_NO: String,
    ROLE: String,
    SECTION_VERIFICATION: String,
    USER_VERIFICATION_CODE: String,
    SECTION_ACCOUNT: String,
    ID: String,
    PASSWORD: String,
    LANGUAGE: String,
    DETAIL_INFORMATION: String,
    PROFORMA: String,
    RULE: String,
    NOTE: String,
    BOX_CONFIGURATION: String,
    SECTION_DISPLAY_CONFIRMATION: String,
    NEXT_SYNC: String,
    CONFIRMATION: String,
    SECTION_FOR_EXPORTER_ONLY: String,
    MARKETING: String,
    ORDER_TYPE: String,
    ORDER_BATCH: String,
    CLOSE_ORDER_DATE: String,
    FORCE_CLOSE_ORDER: String,
    CRM_SECTION: String,
    CUSTOMER_KEY: String,
    CRM_DASHBOARD: String,
    SUB_SECTION_CITES: String,
    CITES_TYPE: String,
    CITES_COMBO: String,
    CITES_SCLERACTINIAN_FRAGMEN: String,
    NO_CITES_1: String,
    NO_CITES_2: String,
    NO_CITES_3: String,
    NO_CITES_4: String,
    NO_CITES_5: String,
    NO_CITES_6: String,
    NO_CITES_7: String,
    NO_CITES_8: String,
    NO_CITES_9: String,
    NO_CITES_10: String,
    CITES_CULTURE: String,
    CITES_WILD: String,

    // Section Rate
    SECTION_RATE: String,
    CRM_PACKING_CHARGE_HD_BOXES: String,
    CRM_CITES_CHARGE_CULTURE_CORAL: String,
    CRM_CITES_CHARGE_WILD_CORAL: String,
    CRM_CITES_PROCESSING_FEE: String,
    CRM_STATEMENT_LETTER_CHARGE: String,
    CRM_DOCUMENT_HANDLING_FEE: String,
    CRM_FISH_PERMIT: String,
    CRM_RATE_100: String,
    CRM_RATE_250: String,
    CRM_RATE_300: String,
    CRM_RATE_500: String,
    CRM_RATE_1000: String,
    CRM_AWB_CCC_FEE: String,
    CRM_VAT_FEE: String,
    CRM_PICKUP: String,

    // Section Discount
    SECTION_DISCOUNT: String,
    RHCC_DISCOUNT: String,
    RHCW_DISCOUNT: String,
    RSCC_DISCOUNT: String,
    RSCW_DISCOUNT: String,
    RANE_DISCOUNT: String,
    GHCC_DISCOUNT: String,
    GHCW_DISCOUNT: String,
    GSCC_DISCOUNT: String,
    GSCW_DISCOUNT: String,
    GANE_DISCOUNT: String,
    FISC_DISCOUNT: String,
    FISW_DISCOUNT: String,
    INVR_DISCOUNT: String,

    // Section Menu Setting
    SECTION_MENU_SETTING: String,
    DEMO_MODE: String,
    TRANSHIPMENT_MODE: String,
    CITES_DISPLAY: String,
    LANDED_COST_DISPLAY: String,
    PRICE_MARGIN: String,
    FREIGHT_MARGIN: String,
    IMPORT_DUTIES: String,

    // Section User Summary Order
    SECTION_USER_SUMMARY_ORDER: String,
    CRM_REFERENCE: String,
    ORDER_CULTURE_CORAL: Number,
    ORDER_WILD_CORAL: Number,
    ORDER_NON_CITES_CORAL: Number,
    ORDER_FISH: Number,
    TOTAL_ORDER: Number,
    AMOUNT_BEFORE_MARGIN: String,
    AMOUNT: String,
    WEIGHT: Number,
    VOLUME: Number,
    TAX: String,
    BOX: Number,
    NON_CITES_BOX: Number,
    TOTAL_BOX: Number,

    // Section Freight & Cost
    SECTION_FREIGHT_COST: String,
    PACKING_CHARGE_HD_BOXES: String,
    CITES_CHARGE_CULTURE_CORAL: String,
    CITES_CHARGE_WILD_CORAL: String,
    CITES_PROCESSING_FEE: String,
    STATEMENT_LETTER_CHARGE: String,
    DOCUMENT_HANDLING_FEE: String,
    FISH_PERMIT: String,
    RATE: String,
    FREIGHT_CHARGE_ALL_IN: String,
    AWB_CCC_FEE: String,
    VAT_FEE: String,
    PICKUP: String,
    IMPORT_FEE: String,
    TOTAL_LANDED_COST_BEFORE_MARGIN: String,
    TOTAL_LANDED_COST: String,
    TOTAL_COST_BEFORE_MARGIN: String,
    TOTAL_COST: String,
    PROFIT: String,

    // Section Unpacking
    SECTION_UNPACKING: String,
    SCAN: String,
    EXPORTER_ONLY: String,
    NEW_LINE: String,
    NEW_AQUARIUM: String,
    NEW_NUMBER: String,

    // Discount RHCC - INVR
    RHCC: String,
    RHCW: String,
    RSCC: String,
    RSCW: String,
    RANE: String,
    GHCC: String,
    GHCW: String,
    GSCC: String,
    GSCW: String,
    GANE: String,
    FISC: String,
    FISW: String,
    INVR: String,
}, { timestamps: true });

const UserGsheet = mongoose.model("UserGsheet", UserGsheetSchema);
export default UserGsheet;
